[project]
name = "sklearn-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=2.3.2",
    "polars>=1.36.1",
    "scikit-learn>=1.8.0",
]
